@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNmVlNjc1MS0zZDFiLTRmNDAtOTkwMC04MjJlNTYyNzUyNWIiLCJpYXQiOjE3MTM0NDQ0NTIsImV4cCI6MTcxNDA0OTI1Mn0.uwu0ytOG2fL_GfTMYvagWkVaMPpghTDOre-vsaAnNFc

### 건의 하기
POST {{endpoint}}/suggestion
Content-Type: application/json

{
  "title": "title1",
  "content": "sdjfklsdjfklsdjfklsdjlfk sdklfjdklsjfl"
}