@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYzYwODc4Ni01MzFjLTQxNzYtOWJlZS04ODlkMGRkMzUwNGYiLCJpYXQiOjE3MTQ1NDUyNTMsImV4cCI6MTcxNTE1MDA1M30._wAG3retzFbvxbdfKKpZmliyXmHeI_0q6MA7hXcrckY


### 툰 생성
POST {{endpoint}}/toons
Cookie: accessToken={{accessToken}}
Content-Type: application/json

{
  "title": "카카오계정이 만든 그림",
  "headCount": 2,
  "timer": 12
}

### 툰 정보 조회
GET {{endpoint}}/toons/b0350f1f-eeba-4ad3-bedc-0ad06e4042ed

### 툰 락 획득
GET {{endpoint}}/toons/5e407e9b-bb09-4b28-ab92-4fa2494f7271/lock

### 툰 그리기
PUT {{endpoint}}/toons/5e407e9b-bb09-4b28-ab92-4fa2494f7271
Content-Type: application/json

{
  "name": "name1",
}

### 내가 만든 툰 리스트 조회
GET {{endpoint}}/toons/owned?completed=false&page=1
Cookie: accessToken={{accessToken}}

### 참여한 툰 리스트 조회
GET {{endpoint}}/toons/participated?completed=true
Cookie: accessToken={{accessToken}}