@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0MGQ5MWVlYy1mNDdmLTQ5YjktOTQxYy1hNThhZWVjNTRkNTMiLCJpYXQiOjE3MTMzNjI5NDksImV4cCI6MTcxMzk2Nzc0OX0.RcWMc_N5TvYlkZsL0JDg6Ybc7gTMlJtzuQgFG1PZ52U

### 툰 생성
POST {{endpoint}}/toons
Cookie: accessToken={{accessToken}}
Content-Type: application/json

{
  "title": "title1",
  "headCount": 2
}