@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NmZiOTAzNy00ZWI4LTRiN2ItYjRhMS0xNDJiZWY2YmJkOTEiLCJpYXQiOjE3MTM1MjQ2MjIsImV4cCI6MTcxNDEyOTQyMn0.mjtIWds62OioEAjjFvzQAnqT5DxaUnK8PXj4PxfJodc

### 유저 정보 조회
GET {{endpoint}}/users/me
Cookie: accessToken={{accessToken}}

