@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYzYwODc4Ni01MzFjLTQxNzYtOWJlZS04ODlkMGRkMzUwNGYiLCJpYXQiOjE3MTQ1NDUyNTMsImV4cCI6MTcxNTE1MDA1M30._wAG3retzFbvxbdfKKpZmliyXmHeI_0q6MA7hXcrckY


### 유저 정보 조회
GET {{endpoint}}/users/me
Cookie: accessToken={{accessToken}}

### 유저 이름 변경
PUT {{endpoint}}/users/me
Cookie: accessToken={{accessToken}}
Content-Type: application/json

{
  "name": "마포 반고흐"
}

### 회원 탈퇴
DELETE {{endpoint}}/users/me
Cookie: accessToken={{accessToken}}
