@endpoint = http://localhost:8000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYzc3MTBkZS1mZmQ3LTQ0NTctYTliNy02ZTE1YWIzMDhkOGIiLCJpYXQiOjE3MTM1Mjc4MzgsImV4cCI6MTcxNDEzMjYzOH0.nsl1oCPLJ6ShYUis32eYJXUG7ghGXkUE5tKxYqir7Qk

### 유저 정보 조회
GET {{endpoint}}/users/me
Cookie: accessToken={{accessToken}}

### 유저 이름 변경
PUT {{endpoint}}/users/me
Cookie: accessToken={{accessToken}}
Content-Type: application/json

{
  "name": "마포 반고흐"
}

### 회원 탈퇴
DELETE {{endpoint}}/users/me
Cookie: accessToken={{accessToken}}
